# Generated by Django 5.0.3 on 2024-03-11 13:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_licenseinfo_customuser_hdd_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LicenseInfo",
        ),
    ]
